name: Build-CVs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # Optional: install extra fonts so the reference template renders consistently
      - name: Install extra fonts (optional)
        run: |
          sudo apt-get install -y fonts-liberation fonts-dejavu-core

      - name: Convert markdown → DOCX with custom template
        run: |
          pandoc resume_us.md \
            --from=gfm \
            --reference-doc=reference.docx \
            --output=resume_us.docx \
            --standalone

          pandoc cv_eu.md \
            --from=gfm \
            --reference-doc=reference.docx \
            --output=cv_eu.docx \
            --standalone

      - uses: actions/upload-artifact@v4
        with:
          name: CVs
          path: |
            resume_us.docx
            cv_eu.docx
